version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ${OLLAMA_VOLUME_PATH:-ollama}:/root/.ollama
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - OLLAMA_HOST=http://ollama:11434
    env_file:
      - stack.env
    depends_on:
      - ollama
volumes:
  ollama:
